## The functions of makeCacheMatrix and cacheSolve are designed to
## take as input a square matrix that can be inverted and return its inverse
## They are intended to promote efficiency by cacheing the results
## so that computation is avoided if the matrix to be inverted has not changed.
## Example use:
##    x <- matrix(1:4,2,2);  y <- makeCacheMatrix(x)
##    cacheSolve(x,y).
## Note the functions do not check that the matrix input is invertible
## and will fail if this condition is not adhered to.



## makeCacheMatrix takes as its argument a square matrix which can be inverted.
## It returns a list containing functions to get and set the matrix values
## and their inverse

makeCacheMatrix <- function(x = matrix()) {
    m <- NULL             # initial value for the inverse matrix
    set <- function(y) {  # update the stored matrix if it has changed
                x <<- y
                m <<- NULL
    }
    get <- function() x  # return the currently stored matrix
    setInverse <- function(solve) m <<- solve  # set inverse to value passed in    
    getInverse <- function() m  # retrieve the stored inverse
    list(set=set,get = get,
         setInverse = setInverse,
         getInverse = getInverse)
}


## cacheSolve takes as input the list generated by makecacheMatrix
## it also takes in the matrix to be inverted.
## It checks to see if an inverse has already been calculated
## and that the matrix passed in has identical values to the last checked.
## if so, it informs the user it is using cached data then returns this. 
## If not, it calculates, stores and returns the inverse matrix.

cacheSolve <- function(x,y, ...) {
        ## Return a matrix that is the inverse of 'x'
    data <- x$get()  # retrieve currently stored matrix
    if (!identical(data,y))  { # true if matrix has changed
        x$set(y)  # matrix changed, so update it in makeCacheMatrix
        data <- y # and use the matrix passed in in local variable
    }
    m <- x$getInverse()  # retrieve currently stored inverse
    if(!is.null(m)) { # true if already cached
            message("getting cached data")
            return(m)  # so return the cached version
    }
    
    m <- solve(data, ...) # compute the inverse
    x$setInverse(m)  # update the inverse stored in makeCacheMatrix
    m  # return the inverse
}
