## The functions of makeCacheMatrix and cacheSolve are designed to
## take as input a square matrix that can be inverted and return its inverse
## They are intended to promote efficiency by cacheing the results
## so that computation is avoided if the matrix to be inverted has not changed.
## Example use:
##    x <- matrix(1:4,2,2);  y <- makeCacheMatrix(x)
##    cacheSolve(y).
## Note the functions do not check that the matrix input is invertible
## and will fail if this condition is not adhered to.



## makeCacheMatrix takes as its argument a square matrix which can be inverted.
## It returns a list containing functions to get and set the matrix values
## and their inverse

makeCacheMatrix <- function(x = matrix()) {
    m <- NULL
    get <- function() x
    setInverse <- function(solve) m <<- solve
    getInverse <- function() m
    list(get = get,
         setInverse = setInverse,
         getInverse = getInverse)
}


## cacheSolve takes as input the list generated by makecacheMatrix
## It checks to see if an inverse has already been calculated
## and informs the user it is using cached data then returns this. 
## If not, it calculates, stores and returns the inverse matrix.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
    m <- x$getInverse()
    if(!is.null(m)) {
            message("getting cached data")
            return(m)
    }
    data <- x$get()
    m <- solve(data, ...)
    x$setInverse(m)
    m
}
